#What is Numpy?


Numpy is a python library provides you with an array data structure that holds some benefits over Python lists, such as: being more compact, faster access in reading and writing items, being more convenient and more efficient.

In other words, NumPy is a Python library that is the core library for scientific computing in Python. It contains a collection of tools and techniques that can be used to solve on a computer mathematical models of problems in Science and Engineering. One of these tools is a high-performance multidimensional array object that is a powerful data structure for efficient computation of arrays and matrices.

We will create numpy arrays using python and numpy library.
Numpy array comes in 2 flavours : 
1. 1D Vector
2. 2D Matrix



#Creating a normal List

> 




In [ ]:
my_list=[1,2,3]
my_list 


[1, 2, 3]

#Casting a normal python list into a numpy array

NumPy library follows an import convention: when you import this library, you have to make sure that you import it as **np**. By doing this, you’ll make sure that other Pythonistas understand your code more easily.

In [ ]:
import numpy as np
a=np.array(my_list)


In [ ]:
my_mat=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
s=np.array(my_mat)

#Numpy own genatation method

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#Numpy also provides many functions to create arrays:

In [ ]:
import numpy as np

a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((4,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [ ]:
np.eye(5) #identitity matrix(2d square matrix)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
#creating arrays of random numbers
np.random.rand(5) #uniform distribution from 0 to 1

array([0.52792564, 0.38232087, 0.04358896, 0.71681335, 0.82747038])

In [ ]:
#creating arrays of random numbers
np.random.rand(5,5) # 2D uniform distribute from 0 to 1

array([[0.00096218, 0.69931721, 0.38219442, 0.0782033 , 0.31911911],
       [0.94425415, 0.5936098 , 0.4817365 , 0.61660807, 0.70231679],
       [0.8622043 , 0.78431941, 0.20507351, 0.14500071, 0.09700329],
       [0.32229101, 0.41705564, 0.30928368, 0.54443478, 0.69404968],
       [0.15926336, 0.12905356, 0.48651418, 0.8175491 , 0.38234886]])

In [ ]:
#creating arrays of random numbers
np.random.randn(4) # standard normal distribution range from -infinty to infinity

array([ 0.58162291, -0.63731864,  0.83470347,  1.72916995])

In [ ]:
#creating arrays of random numbers
np.random.randint(1,100,20)    

array([33, 63,  8, 43, 25, 68, 34, 52, 13, 74, 99,  2, 33, 52, 38, 36, 82,
       96, 21, 11])

In [ ]:
#gives you 6 numbers randomly from 0-(10-1)
x1 = np.random.randint(10, size=6)
x1

array([3, 8, 0, 3, 6, 7])

In [ ]:
x2 = np.random.randint(10, size=(3,4,3))
print(x2)
print(x2.shape)
print(f"Dimensiion = {x2.ndim}")

[[[7 9 9]
  [8 5 9]
  [4 2 3]
  [9 7 8]]

 [[0 0 4]
  [5 1 0]
  [0 4 5]
  [3 1 9]]

 [[7 2 7]
  [9 1 1]
  [9 4 8]
  [8 6 0]]]
(3, 4, 3)
Dimensiion = 3


In [ ]:
#creating max and min value in array
my_arr=np.array([1,-3,4,5,3,4,56,7,-34])
print(my_arr.min())
print(my_arr.max())

-34
56


In [ ]:
#returning index number max and min value in array
print(my_arr.argmin())
print(my_arr.argmax())

0
2


In [ ]:
#how to find the shape of vector?
my_arr.shape

(9,)

In [ ]:
#how to reshape vector?
my_arr.reshape(3,3)


numpy.ndarray

In [ ]:
#how to know  what the data type value we have in array ?
print(type(my_arr))
print(my_arr.dtype)

<class 'numpy.ndarray'>
int64


In [ ]:
#append
import numpy as np
new_arr=np.arange(1,11)
print(new_arr)
new_arr= np.append(new_arr,[100,20,30])
print(new_arr)

[ 1  2  3  4  5  6  7  8  9 10]
[  1   2   3   4   5   6   7   8   9  10 100  20  30]


In [ ]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a)
b= np.array([[400],[800]])
print(b)
newarr = np.append(a, b,axis=1 )
print(newarr)

[[1 2 3]
 [4 5 6]]
[[400]
 [800]]
[[  1   2   3 400]
 [  4   5   6 800]]


In [ ]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
b= np.array([[400],[800]])
newarr = np.append(a, b)
print(newarr)

[  1   2   3   4   5   6 400 800]


In [ ]:
#insert
a= np.array([1 , 2, 3])
print( a) 
new_array= np.insert(a,1,50)
print(new_array)

[1 2 3]
[ 1 50  2  3]


In [ ]:
#delete
import numpy as np
a = np.array([[1,2,3],[4,5,6],[10,20,30]])

print(a)
narr = np.delete(a,1,axis=0)
print(narr)

[[ 1  2  3]
 [ 4  5  6]
 [10 20 30]]
[[ 1  2  3]
 [10 20 30]]


In [ ]:
#finding the index of a value in the array usin where() method
a = np.array([1 , 2 ,3, 5 ,4 ,5])
print(np.where(a==5))

(array([3, 5]),)


#Numpy Indexing and Selection


In [ ]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
a[1,0]

4

In [ ]:
a[1:,1:]


array([[5, 6],
       [8, 9]])

In [ ]:
a[:2,1:]

array([[2, 3],
       [5, 6]])

In [ ]:
#conditional selection
b = a > 2  #take an array and combine with conditional operate to get a boolean values/arrays
print(b)

[[False False  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
#return only those elements those were true using bollean array
x=a[b] 
x.shape

(7,)

In [ ]:
#in one go!!
a[a>3]

array([4, 5, 6, 7, 8, 9])

In [ ]:
a1 = np.array([[1,2,3],[4,5,6],[9,10,11]])
print(a1)

[[ 1  2  3]
 [ 4  5  6]
 [ 9 10 11]]


In [ ]:

a1[a1<=2]=1
a1[a1>2]=0
a1

array([[1, 1, 0],
       [0, 0, 0],
       [0, 0, 0]])

#NumPy Operations

In [ ]:
import numpy as np
arr=np.arange(0,11)
arr2=np.arange(0,11)
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#addition
arr+arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
#substraction
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
#multiplication
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [ ]:
arr/arr

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
#scaling an array
arr+100
#to the power
#squareroot
#sin
#log
#max/min

https://numpy.org/doc/stable/reference/ufuncs.html#:~:text=That%20is%2C%20a%20ufunc%20is,implemented%20in%20compiled%20C%20code.


SyntaxError: ignored